### ISSUE TITLE
flat file validator: ERROR: Abutting features - but 2 different genes

### ISSUE THREAD

**Issue by Juke34** [enasequence/sequencetools#22] opened 2017-11-10 13:25 UTC
Hi, 

I think I maybe catched up a problem.
I got this error message:  **ERROR: Abutting features cannot be adjacent between neighbouring exons.** 

But the exons come from two different genes. So it shouldn't pop up this error, isn't it ?

Here the incriminated data:
FT                   /locus_tag="XXX_locus9"
FT                   /standard_name="nd3"
FT   mRNA            complement(33552..33983)
FT                   /locus_tag="XXX_locus9"
FT                   /db_xref="PFAM:PF00507"
FT                   /db_xref="InterPro:IPR000440"
FT                   /standard_name="nd3"
FT                   /product="NADH-ubiquinone oxidoreductase chain 3"
FT   exon            complement(33552..33983)
FT                   /locus_tag="XXX_locus9"
FT   CDS             complement(33552..33983)
FT                   /standard_name="997d301c-292f-4298-a95d-d0e781219055-CDS"
FT                   /locus_tag="XXX_locus9"
FT                   /transl_table=3
FT   gene            complement(33984..35597)
FT                   /locus_tag="XXX_locus10"
FT                   /standard_name="nad2"
FT   mRNA            complement(33984..35597)
FT                   /locus_tag="XXX_locus10"
FT                   /db_xref="PFAM:PF00361"
FT                   /db_xref="InterPro:IPR001750"
FT                   /standard_name="nad2"
FT                   /product="NADH-ubiquinone oxidoreductase chain 2"
FT   exon            complement(33984..35597)
FT                   /locus_tag="XXX_locus10"
FT   CDS             complement(33984..35597)
FT                   /standard_name="9c34554f-87af-4487-9ca0-7c72af721aff-CDS"
FT                   /locus_tag="XXX_locus10"
FT                   /transl_table=3

**Comment by raskoleinonen** [comment] 2018-01-03 16:13
This check was added December 2014 and does not account for abutting exons in different genes. It might be best for us to remove this check for the time being.

**Comment by loraine-gueguen** [comment] 2018-04-05 13:33
Same use case as @Juke34 (exons come from two different genes)

**Comment by rob123king** [comment] 2020-04-17 10:37
This is still coming up as an error when submitting sequences to ENA when the gene is correct. How do I submit if the validator is making this mistake and won't let me progress?

**Comment by raskoleinonen** [comment] 2020-04-17 10:50
My apologies. We will look into this shortly (internal ticket number: ENA-3727). We will address the problem and create a new fixed Webin-CLI release.

**Comment by raskoleinonen** [comment] 2020-04-20 10:23
Response from ENA curators ->

This looks odd as it looks like the two genes are single exon and have the same coordinates as the respective mRNAs although this is biologically possible. This error is being thrown as there is no intronic sequence  between the two genes, i.e the genes are adjacent. I think the error message is correct although a little misleading as it mentions exons (which would normally be the case for the same gene) but it is actually genes in this case.

**Comment by Juke34** [comment] 2020-04-20 10:59
As genes can overlap I don't see why they cannot be adjacent. This if often due to tool limitation and underlying sequence. There are lot of cases like that because gene predictors evidence-based or evidence-driven do not know how to deal with continious transcription signal between two coding sequences (CDS), they are UTR parts that overlap at some point

**Comment by rob123king** [comment] 2020-04-24 14:43
As above described, the issue is, that automatic gene predictors sometimes have UTR which also go right up against each other in opposite directions and sometimes coding sequence, plus in the same direction. Although likely incorrect, such as snp in genome causing a break or overlapping transcriptome evidence, without a tool to fix this, it is an absolute nightmare to fix. There will be lots of inaccuracies in gene predictions but it shouldn't fail for that, as this is an ongoing curation and tool improvement issue. An annotation is never 100% correct. As long as the parent child relationships are there, and exons, UTR etc have the correct boundaries, why add more problems to people submitting data. It is already a massive time undertaking for annotated genomes to submit. Also the mitochondria submission issue I have, has two genes as described in opposite directions but no gap and taken from NCBI annotation that I transferred so NCBI don't flag it as an error so to be consistent, it would be good if ENA tools also didn't flag it. I think the abutting rule should go in short. I think quite often what is practically appropriate and what is textbook correct need compromising in the real world.

**Comment by raskoleinonen** [comment] 2020-04-27 14:27
Thank you very much for the detailed explanation. We will remove this validation and the validation error. We will try to prioritise this work.

**Comment by raskoleinonen** [comment] 2020-04-30 14:48
We have released a new version of Webin-CLI that should address this issue:
https://github.com/enasequence/webin-cli/releases/tag/v2.2.4

**Comment by raskoleinonen** [comment] 2020-05-05 13:40
Confirmed fixed in Webin-CLI 2.2.4. Unusually Webin-CLI 2.2.4 was released twice in quick succession. First version without and the second version with this fix.

**Closed by raskoleinonen** 2020-05-05 13:40 UTC

**Comment by tothuhien** [comment] 2025-08-25 07:52
Do you think abutting exons of the same gene but from 2 different transcripts should be also allowed, @raskoleinonen ? Thanks.

**Comment by Juke34** [comment] 2025-08-25 09:32
The easiest is to avoid to submit the exons. The exons are anyway implicitly described within the mRNA feature via star/end locations so no need to include them as feature.

Using EMBLmyGFF3 I usually do 
```
EMBLmyGFF3 --expose_translations
```
then change the ` translation_gff_feature_to_embl_feature.json` file to say the tool to throw the exons:
```
"exon": {
    "remove": true
}
```


Otherwise (but not recommended) there is a script in AGAT (https://github.com/NBISweden/AGAT/blob/master/bin/agat_sp_fix_features_locations_duplicated.pl) that will add or remove +1 nucleotide in order that identical exons from isoforms are slightly different. It works only on exons where we can add or stretch an UTR (It will not touch a CDS). It needs a GFF/GTF annotation file, then you must convert your annotation in EMBL flat file.

**Comment by tothuhien** [comment] 2025-08-25 17:10
Thanks @Juke34 for the suggestion!
